=== engle206/Client-project/client.dtd
<!ELEMENT portfolio (painting+)> 
<!Element painting (title, color, theme, style, height-inches, width-inches)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT theme (#PCDATA)>
<!ELEMENT style (#PCDATA)>
<!ELEMENT height-inches (#PCDATA)>
<!ELEMENT width-inches (#PCDATA)>

=== engle206/Client-project/mollywebsite.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogue SYSTEM "client.dtd">
<portfolio>
      <title></title>
      <color></color>
      <theme></theme>
      <style></style>
      <height-inches></height-inches>
      <width-inches></width-inches>
</portfolio>

<portfolio>
    <title>Anatomical Red Heart</title>
    <color>
      <color 1>Red</color 1>
      <color 2>Black</color 2>
      <color 3>White</color 3>
    </color>
    <theme>Anatomically Accurate</theme>
    <style>Water Color</style>
    <height-inches>14</height-inches>
    <width-inches>11</width-inches>
</portfolio>
<portfolio>
    <title>Cow Skull</title>
    <color>
      <color 1>Black</color 1>
      <color 2>White</color 2>
    </color>
    <theme>Anatomically Accurate</theme>
    <style>Single line pen</style>
    <height-inches>14</height-inches>
    <width-inches>11</width-inches>
</portfolio>
<portfolio>
    <title>Moon</title>
    <color>
      <color 1>Blue</color 1>
      <color 2>Black</color 2>
      <color 3>White</color 3>
    </color>
    <theme>Nature</theme>
    <style>Oil Paint</style>
    <height-inches>14</height-inches>
    <width-inches>11</width-inches>
</portfolio>
